
#pragma once

#define DEVICE_NAME_UUID "0x2a00"
#define APPEARANCE_UUID "0x2a01"

#define DEVICE_INFORMATION_SERVICE_UUID "0x180A"
#define MODEL_NUMBER_UUID "0x2A24"
#define SERIAL_NUMBER_UUID "0x2A25"
#define FIRMWARE_REVISION_UUID "0x2A26"
#define HARDWARE_REVISION_UUID "0x2A27"
#define SOFTWARE_REVISION_UUID "0x2A28"
#define MANUFACTURER_NAME_UUID "0x2A29"
